// Single source of truth for permission keys (based on route map).  :contentReference[oaicite:2]{index=2}
const PERMS = {
  USER_READ: "user.read",
  USER_WRITE: "user.write",
  ROLE_READ: "role.read",
  ROLE_WRITE: "role.write",
  PRICE_MANAGE: "price.manage",
  AUDIT_READ: "audit.read",
  PATIENT_READ: "patient.read",
  PATIENT_WRITE: "patient.write",
  APPT_READ: "appointment.read",
  APPT_WRITE: "appointment.write",
  QUEUE_NEXT: "queue.next",
  ENCOUNTER_READ: "encounter.read",
  ENCOUNTER_WRITE: "encounter.write",
  NOTE_WRITE: "note.write",
  VITALS_WRITE: "vitals.write",
  DIAG_WRITE: "diagnosis.write",
  PROC_WRITE: "procedure.write",
  PRESC_WRITE: "prescription.write",
  LAB_ORDER: "lab.order",
  LAB_RESULT: "lab.result",
  RAD_ORDER: "rad.order",
  RAD_REPORT: "rad.report",
  PHARM_DISPENSE: "pharmacy.dispense",
  EMAR_ADMIN: "emar.administer",
  ADMIT: "ipd.admit",
  TRANSFER: "ipd.transfer",
  DISCHARGE: "ipd.discharge",
  INVOICE_WRITE: "billing.invoice",
  PAYMENT_WRITE: "billing.payment",
  REFUND_WRITE: "billing.refund",
  CLAIM_WRITE: "claim.write",
  CLAIM_SUBMIT: "claim.submit",
  ITEM_WRITE: "inv.item",
  GRN_WRITE: "inv.grn",
  TRANSFER_WRITE: "inv.transfer",
  ADJUST_WRITE: "inv.adjust",
  LEDGER_READ: "inv.ledger",
  CSSD_WRITE: "cssd.write",
  FILE_UPLOAD: "file.upload",
  FILE_READ: "file.read",
  NOTIFY_SEND: "notify.send",
};
module.exports = { PERMS };
